language: perl

sudo: false

install:
  - curl https://alienfile.org/travis/install-system-dontpanic.sh | bash -
  - curl https://alienfile.org/travis/install-system-acme-alien-dontpanic.sh | bash -
  - ./maint/travis-install-mods
  - dzil authordeps --missing | cpanm -n
  - dzil listdeps  --missing | cpanm -n

perl:
  - "5.22"
  - "5.24"
  - "5.26"
  - "5.28"
  - "5.30"

script:
  - dzil test -v

env:
  global:
    - PATH=$PATH:$HOME/opt/dontpanic/current/bin
    - LD_LIBRARY_PATH=$HOME/opt/dontpanic/current/lib
    - PKG_CONFIG_PATH=$HOME/opt/dontpanic/current/lib/pkgconfig
    - PERL_CPANM_OPT='--mirror https://cpan.metacpan.org/ --mirror-only'
    - PERL_USE_UNSAFE_INC=0
  matrix:
    - ALIEN_INSTALL_TYPE=share
    - ALIEN_INSTALL_TYPE=system

  
