language: perl

sudo: false

install:
  - curl https://perl5-alien.github.io/static/travis/install-system-dontpanic.sh | bash -
  - curl https://perl5-alien.github.io/static/travis/install-system-acme-alien-dontpanic.sh | bash -
  - ./maint/travis-install-alienbuild
  - dzil authordeps --missing | cpanm -n
  - dzil listdeps  --missing | cpanm -n

perl:
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"

script:
  - dzil test -v

env:
  global:
    - PATH=$PATH:$HOME/opt/dontpanic/current/bin
    - LD_LIBRARY_PATH=$HOME/opt/dontpanic/current/lib
    - PKG_CONFIG_PATH=$HOME/opt/dontpanic/current/lib/pkgconfig
    - PERL_CPANM_OPT='--mirror https://cpan.metacpan.org/ --mirror-only'
  matrix:
    - ALIEN_INSTALL_TYPE=share
    - ALIEN_INSTALL_TYPE=system

  
